### PR TITLE
Update applicationSettings.cfm

### PR DESCRIPTION
**Pull request by nsollecito**
Conditionally setting `this.datasource.username` and `this.datasource.password` based on if it has a length is causing significant problems with Slatwall and other plugins since these values are explicitly being passed into queries and other tags where a datasource is present. 

Setting them in cfapplication.cfm doesn't seem to help so reverting back to having default values for these is the only workaround I've found that works with some of our stuff on Mura 7. Let me know if you have any concerns.

### CODE REVIEW

**Comment by mattlevine** [comment]
I can't accept this pull request because what you're taking is was out fix to allow transactions to work with Mura ORM.  Does adding this to the /config/cfapplication.cfm help?

```
<cfset this.datasource.username = "">
 <cfset this.datasource.password = "">
```

**Comment by nsollecito** [comment]
No, that was my first approach. Didn't help
***************************************************************************
DISCLAIMER: This e-mail is confidential and should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage mechanism. Neither Macmillan Publishers Limited nor Macmillan Publishers International Limited nor any of their agents accept liability for any statements made which are clearly the sender's own and not expressly made on behalf of Macmillan Publishers Limited or Macmillan Publishers International Limited or one of their agents. 
Please note that neither Macmillan Publishers Limited nor Macmillan Publishers International Limited nor any of their agents accept any responsibility for viruses that may be contained in this e-mail or its attachments and it is your responsibility to scan the e-mail and attachments (if any). No contracts may be concluded on behalf of Macmillan Publishers Limited or Macmillan Publishers International Limited or their agents by means of e-mail communication. 
Macmillan Publishers Limited. Registered in England and Wales with registered number 785998. 
Registered Office The Campus, 4 Crinan Street, LONDON, N1 9XW
Macmillan Publishers International Limited. Registered in England and Wales with registered number 02063302. 
Registered Office Cromwell Place, Hampshire International Business Park, Lime Tree Way, Basingstoke, HAMPSHIRE RG24 8YJ
Pan Macmillan, Priddy and MDL are divisions of Macmillan Publishers International Limited. 
Macmillan Publishers Limited trading as Macmillan Education, Language Learning, Schools, Palgrave, Nature Research and  Palgrave Macmillan.
********************************************************************************

**Comment by mattlevine** [comment]
Can you pull down the latest from develop and retest?

**Comment by mattlevine** [comment]
Nevermind that idea doesn't work.  I'm going to have to table this until I get back from vacation.

**Comment by nsollecito** [comment]
@gregmoser Has ten24 run into this problem with Mura 7?

**Comment by gregmoser** [comment]
@nsollecito that would imply that we have people running on mura 7 at this point :)

Can you give me an example of a query in Slatwall where you are getting the error?

**Comment by nsollecito** [comment]
@gregmoser - SW blows up right here saying this.datasource.username is not defined:
https://github.com/ten24/slatwall/blob/master/config/configORM.cfm#L3

When you have your username and password saved as part of the datasource and not defined in settings.ini.cfm.

If you were to set the username and password in settings.ini.cfm, everything should work fine.

**Comment by gregmoser** [comment]
This is starting to feel familiar now.  So here is the deal, we default un/pw in Hibachi.cfc at beginning of our request lifecycle here:
https://github.com/ten24/slatwall/blob/master/org/Hibachi/Hibachi.cfc#L12-L13

But then we do this include:
https://github.com/ten24/slatwall/blob/master/org/Hibachi/Hibachi.cfc#L18

And when integrated with mura, that file will pull in the mura application settings here:
https://github.com/nature/sams/blob/master/Slatwall/custom/config/configApplication.cfm#L1-L3

Because of those includes to the core mura application, the this.datasource.username & password get blow away when mura sets this.datasource to structNew here:
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L252

A very quick fix to you issue would be just to re-set the this.datasource.username & password AFTER the mura includes in this file:
https://github.com/nature/sams/blob/master/Slatwall/custom/config/configApplication.cfm

That file is upgrade safe and considered to be "SciAm" code.

We should find a more permanent solution to this problem.  @mattlevine I have 2 options.

1) In mura, you check to see if this.datasource exists before just setting it to structNew() although our defaulting of un/pw might then cause the same issue you were trying to avoid.

2) We could update our mura integration to automatically add those 2 defaults back to the /custom/config/configApplication.cfm file on install.  Again however I don't know enough about mura ORM to know if this would be an issue.

**Comment by nsollecito** [comment]
thanks @gregmoser. That should solve the issue for SW. I'll report back any other findings

**Pull request closed without merging**
