### PR TITLE
adding nested form builder icon

### PR DESCRIPTION
**Pull request by ronnieduke**

### CODE REVIEW

**Comment by mattlevine** [comment]
There still seems to be no icon on the added nested form element in the side bar?

**Comment by ronnieduke** [comment]
@mattlevine - try clearing your cache since it's a sprite.

**Comment by mattlevine** [comment]
I did and there's still no icon on the left sidebar panel once added to the stage. In addition the properties panel seem to have the hidden icon.

**Comment by ronnieduke** [comment]
@mattlevine - Okay I see what you mean now. I forgot there was those other instances of the icon. I'll fix and push up shortly.

**Comment by ronnieduke** [comment]
@mattlevine - the new pull should have these in place now. Let me know if you see anything wonky

**Pull request merged**
