### PR TITLE
Fix for not being able to delete class extensions.

### PR DESCRIPTION
**Pull request by dbudde**
The delete button was not set to type='button', so the form was submitting and you could not work with the delete dialog to finish removing a class extension.

### CODE REVIEW

**Comment by mattlevine** [comment]
Would you mind signing and sending back our contributors agreement?

https://github.com/blueriver/MuraCMS/blob/develop/Mura_CMS_contribution_agreement.pdf

Thanks for the help!

**Comment by dbudde** [comment]
Here it is.

**Comment by mattlevine** [comment]
I don't see it.  Perhaps just email it to me at matt.levine@blueriver.com

Thanks again.
-Matt

**Comment by dbudde** [comment]
I just forwarded the e-mail with the PDF to your matt.levine@blueriver.com
address.

Daniel

**Comment by mattlevine** [comment]
Thanks, got it.

**Pull request closed without merging**
