### PR TITLE
Add default styling for new CKeditor image alignment

### PR DESCRIPTION
**Pull request by gowestweb**

### CODE REVIEW

**Comment by mattlevine** [comment]
It seems like this may lead to people having styles in their editor that don't exist in their theme?

**Comment by stevewithington** [comment]
@mattlevine I just took a look, and this should be fine if someone updates their site files. It looks like he's addressed this at both the theme and site level, so I'm fine with it myself.

**Comment by mattlevine** [comment]
But theme's don't auto update, so it would only work on newly built themes.

**Comment by stevewithington** [comment]
@mattlevine understood. I mean that this should be fine if they update their site files and are including "Mura's" css, which most do.

**Comment by mattlevine** [comment]
ah ok

**Comment by stevewithington** [comment]
@mattlevine the issue is when positioning an image in CKEditor, it appends a class to it, and it wasn't defined anywhere. So, this actually fixes that issue as well.

**Comment by gowestweb** [comment]
@stevewithington  thanks for explaining before I could get to it : )  We tried to cover both angles, for sites with an older theme and those using a brand new install.

**Pull request merged**
