### PR TITLE
Update imageinterpolation to highestPerformance

### PR DESCRIPTION
**Pull request by nopjmp**
highestQuality takes 1.703 secs in Raymond Camden's testing on ColdFusion 8. We observed similar behavior on ColdFusion 10 and ColdFusion 11. The quality difference is not noticeable by the naked eye and the user can always change the setting later. 

Source: http://www.raymondcamden.com/2008/11/01/ColdFusion-8-Image-Resize-options

### CODE REVIEW

**Comment by andrew-dixon** [comment]
@nopjmp This is different to conversation I had with @mattlevine on the Google Group where we found the settings:

```
imageinterpolation=highQuality
imageQuality=.85
```

and gave no noticeable difference in image quality and an much better filesize. Not sure on the time taken but it feels faster. Conversation here:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mura-cms-developers/rKL8PqxCblo/Mfrp1FfpBAAJ

**Comment by nopjmp** [comment]
I'll check it out on the next site that causes problems.

The main problem is the default settings do not work well when multiple sites are all trying to resize images at the same time. We haven't had anymore more problems with it in our system so I haven't contacted the Google Group about it.

**Comment by andrew-dixon** [comment]
@nopjmp - I misread this at first, I thought it had been merged, but now I see you closed it.

**Comment by nopjmp** [comment]
I mainly closed it due to the fact that I deleted my fork and there was a discussion on the Google Group I didn't see before. It's a minimal change that can be made in our specific case.

**Pull request closed without merging**
