### PR TITLE
Update loadrelatedcontent.cfm

### PR DESCRIPTION
**Pull request by nsollecito**
Adding locale-specific date formatting for related content search. The dateAdd/formatting for $.event("rcEndDate") was particularly tricky and is working for us currently though I'm not entirely sure if the solution proposed here is ideal.

### CODE REVIEW

**Comment by mattlevine** [comment]
Can you point me the key part of the changes are?  The diff has a bit of noise.

**Comment by nsollecito** [comment]
@mattlevine sorry, check the diff again I fixed it.. The main part of the change is with formatting the dates on the feed

**Comment by mattlevine** [comment]
Looks like you're trying to do this?

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/bean/bean.cfc#L239-L262

**Comment by mattlevine** [comment]
Could perhaps add  the parseDateTimeArg to the mura.utility and use it parse that passed search params.

**Comment by nsollecito** [comment]
The problem we're trying to solve here is preventing DD/MM/YYYY from being applied to the feed as MM/DD/YYYY

**Comment by mattlevine** [comment]
Yeah, that's why the parseDateArg() is for.  I can put something together tomorrow.

**Comment by mattlevine** [comment]
Please open if not fixed

**Pull request closed without merging**
