### PR TITLE
Poll JS Issue: Remove extra character from JS

### PR DESCRIPTION
**Pull request by Reyjay**
There was an extra character in the JS that created an error in the console.

### CODE REVIEW

**Comment by mattlevine** [comment]
Thanks for the help!  I know it's just a minor fix but would you mind signing and sending in a contributor agreement?

https://github.com/blueriver/MuraCMS/blob/develop/Mura_CMS_contribution_agreement.pdf

If not, I'll just manually fix the issue that you pointed out, but it would be great to get that issue sorted for the future.

-Matt

**Comment by Reyjay** [comment]
Hi Matt,

Np.  Document is attached.

-Reyjay

**Comment by mattlevine** [comment]
It's a link in the comment.  It's actually distributed with Mura in the root as well.

https://github.com/blueriver/MuraCMS/blob/develop/Mura_CMS_contribution_agreement.pdf

**Comment by Reyjay** [comment]
I attached it to the last message and this one. Let me know if you have
trouble opening it.

Thanks,
Reyjay

**Comment by mattlevine** [comment]
Sorry I don't think Github does supports attachments for pull request comments.  Please just email it to me at matt.levine@blueriver.com.

Thanks!
-Matt

**Pull request merged**
