### PR TITLE
Setup wizard

### PR DESCRIPTION
**Pull request by cameroncf**
I did a little work during sessions and at the airport on the setup screens for Jaguar. Since the old bootstrap files are totally absent from Jaguar the setup was completely jacked up looking. This converts it to a 3 tab "wizard" with an opportunity to explain a little more along the way. It's still buggy but it's a start. 

Screencast of what it looks like here:
https://dl.dropboxusercontent.com/u/2123009/2016-02-20_1212.swf

Thoughts?

### CODE REVIEW

**Comment by gowestweb** [comment]
This is still very much work in progress. Not ready for prime time by any means. We have plans for this and other things not yet completed.

**Comment by mattlevine** [comment]
Thanks for this, I'm officially zoning out a little this weekend.  But I'll check it out early next week. It was great seeing you at the conference.

**Comment by cameroncf** [comment]
@mattlevine You definitely should take a weekend (or more) and zone out. Great to see you both this week!

@gowestweb I'm dropping in some screen shots for you here too.

screen shot 2016-02-21 at 8 28 23 am
screen shot 2016-02-21 at 8 30 01 am
screen shot 2016-02-21 at 8 30 10 am
screen shot 2016-02-21 at 8 30 17 am
screen shot 2016-02-21 at 8 30 25 am

**Comment by cameroncf** [comment]
Caveat - this wizard is not complete yet. Mainly I am sharing this now in case I get busy at work this week and I forget to share it or never get back to it. If you guys think you will go a totally different direction with this that's okay. Just wanted to share what I'd done.

Quick list of things not yet complete that I can think of right now:

1. Summary of "what we are about to do" between step 3 and "complete screen" so people understand what's about to happen to their setup.
2. I changed some things that were radios into checkboxes, this needs more testing since that probably broke something.
3. I'd like to add a little more instruction text on step 2 and 3 like there is on the database tab.
4. I split out the setup's "index.cfm" into a bunch of smaller files. These need to be refactored a bit more and probably organized a little differently.
5. The original index.cfm is still there for now as a reference but it will need to be killed at some point.

**Comment by seanschroeder** [comment]
This looks great, Cameron! Thanks for sharing!

**Comment by cameroncf** [comment]
After you guys get a chance to look at this, let me know if it's worth me continuing to work on. I am pretty sure we can just leave the Pull Request open and I can keep moving on it till it's good enough to accept into the official jaguar branch. 

This screen is the first thing people see when they try Mura 7 out so it's in all of our best interest to get it looking better short term even if you guys nuke my work later. Right now it's pretty jacked up since it's still trying to use the old admin bootstrap files.

If this work doesn't have a snowball's chance of even making it there at all I'd not want to spend more time on it so just let me know if I headed in a direction that would be accepted. I'd probably push a final fully tested version back to you guys within 3-5 days.

screen shot 2016-02-22 at 9 27 35 am

**Comment by mattlevine** [comment]
It's definitely worth continuing on.  Should I accept it now or as you suggested just leave it open as you tweak things.

-Matt

**Comment by JonasEriksson** [comment]
Hi guys, if I may suggest (you might already have incorporated this) one thing: I love the idea of having Mura set up a database as it does now, but as far as I know it creates a rather random name. So one still needs to go into CF Admin right away to add a comment to the new database and when looking at the databases in MySQL it is far from clear which one belongs to which Mura site when running multiple Mura CMS sites on one server. If one could simply add a variable/prefix, so that the name created was "MuraDB-CLIENTNAME-456789" or similar, that would help with the overall management of the databases in my opinion. I like to think that's quite an easy addition at this stage? In any case, I really like the new look! Great work!

**Comment by cameroncf** [comment]
@mattlevine Let me work on this another day or two and I think it will be ready for you to give it a run. I'll hit you up again once I get it polished up a little more. 

@JonasEriksson Good suggestion. I want to refactor some of that code (some I want to avoid too) so I'll see what I find in there. I don't actually use the "Generate the db for me" option much but I will need to at least make sure I didn't break it with my changes so I'll look at it.

**Comment by cameroncf** [comment]
@mattlevine - Okay I think this is healthy enough to pull into the jaguar branch if you want to. Some notes:
- The entire index.cfm is rewritten and broken out into include files to make it easier to manage.
- Completely removed the mail server setup since it hasn't been used in a long time
- Eliminated a few other form fields that were optional hidden fields and just coded them straight in (ie: assettpath)
- Tried to avoid changing anything in the form processing for the most part
- Primary change to form processing is looking "form" struct instead of fieldnames to make default values work better.
- Didn't touch anything in the db or doa folders
- The "Create database" option is not tested yet
- There are three javascript files from the theme that didn't appear to be in your "oneui.min.js" file. I linked to them remotely in inc/_form.cfm at the bottom. This needs to be moved into your main js file but I didn't want to rock that boat too much.

Some optional things I think that could still be improved:
- Adding RB support
- The DSN name fix that @JonasEriksson suggested above
- Forcing a stronger password by default

Want these are issues in GitHub till they get resolved?

**Pull request merged**
