### PR TITLE
Fix for plugin settings bean when reading xml Attributes.

### PR DESCRIPTION
**Pull request by David-Polehonski**
I ran into this bug when trying to write a plugin for Mura where it was trying to read the xmlText from an xmlAttribute. I updated the code to fix the issue. Tested on Railo.

### CODE REVIEW

**Comment by mattlevine** [comment]
Would you mind signing and sending in a contributors agreement?

https://github.com/blueriver/MuraCMS/blob/master/Mura_CMS_contribution_agreement.pdf

**Comment by David-Polehonski** [comment]
Any update on whether this is eligible for integration? I'm chasing my manager for approval on the contributors agreement.

**Comment by David-Polehonski** [comment]
Steps to repoduce: 
1. Create a plugin with a config.xml which defines the plugin settings with the following style of markup. `<setting name="isSetting"
    		label="Use Setting?"
    		hint="Is this a setting?"
                type="radioGroup"
    		required="true"
    		validation=""
    		regex=""
    		message="Is this a setting? Please select yes or no."
    		defaultvalue="yes"
    		optionlist="true^false"
    		optionlabellist="Yes^No" />`
2. Install plugin and attempt to set the setting in the Mura plugin edit screen. The error reads 'key NAME not found in struct'

**Comment by mattlevine** [comment]
Thanks for point this out. It will be fixed in the next release.  If possible it would still be great to get the contributors agreement for any future issues.

thanks
-Matt

**Comment by David-Polehonski** [comment]
I don't understand, why would you prefer the use of `<cfset evaluate("variables.set#i#(arguments.theXML[i].xmlText)")/>`? Also from what I can read in the fix you referenced it doesn't address the issue in the pluginManager.cfc in the updateSettings function which has the same issue.

**Comment by mattlevine** [comment]
I totally missed the pluginManager issue.  It should now be fixed as well.  The reason that I fix the issue with:

```
<cfset evaluate("set#i#(arguments.theXML.xmlAttributes[i])")/>
```

and not:

```
<cfset variables["set#i#"](arguments.theXML.xmlAttributes[i])/>
```

is because ACF does not support that syntax.  I agree it's much cleaner, but at this point can't be used in Mura core.

**Pull request closed without merging**
