### PR TITLE
Fix 'from' override

### PR DESCRIPTION
**Pull request by beamerweb**
It seems like arguments.from should be used to set the from email. Currently, if you call mailer with a from argument, the from header ends up looking like:

From: <#arguments.from#> #siteConfig.fromEmail#

Which then sends replies to the site's from email address, not the arguments.from. Shoudln't it default to the site's from address ONLY if arguments.from is not specified (as shown by the condition a few lines above each of these changes)?

### CODE REVIEW

**Comment by mattlevine** [comment]
Most email servers only allow you send send from email accounts that it knows about.  This is why Mura send all emails from the same account.

It set's the arguments.from value as the label where the true value is the email address that is configured in the site settings.

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/mailer.cfc#L233

**Comment by beamerweb** [comment]
Right – the problem is, when I want to send from a specific email address, I can’t with mailer.send*().

 

So is the solution to just copy mailer to override that?

 

Jason Beam

Blue River Interactive Group

 <http://www.blueriver.com> www.blueriver.com

 <http://www.getmura.com> www.getmura.com

**Comment by mattlevine** [comment]
Honestly, for you one off item I would just cfmail.  I'm nervous that if I take your request, I'll end up having  a bunch of other problem pop up.

**Comment by beamerweb** [comment]
Understood – we can do that. I wondered about adding a settings.ini flag to “use real from” as an option, but wasn’t sure the ramifications.

 

We can do the one-off, that’s okay.

 

Thanks. 

 

Jason Beam

Blue River Interactive Group

 <http://www.blueriver.com> www.blueriver.com

 <http://www.getmura.com> www.getmura.com

**Comment by Lagaffe** [comment]
What about using replyto instead of from?
It would be awesome of this issue is addressed.

**Pull request closed without merging**
